version: '3.8'

services:
  exabeam-mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - EXABEAM_CLIENT_ID=${EXABEAM_CLIENT_ID}
      - EXABEAM_CLIENT_SECRET=${EXABEAM_CLIENT_SECRET}
      - EXABEAM_BASE_URL=${EXABEAM_BASE_URL:-https://api.us-west.exabeam.cloud}
      - PORT=8080
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - exabeam-mcp-server
    restart: unless-stopped
    profiles:
      - production
